{{- if .Values.acmeCertificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.nameOverride }}
  {{- if .Values.istioIngress.enabled }}
  namespace: istio-system
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{-  end }}
spec:
  {{- if .Values.istioIngress.enabled }}
  dnsNames:
    - {{ .Values.istioIngress.hostname }}
  {{- end }}
  {{- if .Values.ingress.enabled }}
    {{- with (first .Values.ingress.hosts) }}
  dnsNames:
    - {{ .host }}
    {{- end}}
  {{- end}}
  {{- if .Values.ingressRoute.enabled }}
  dnsNames:
    - {{ .Values.acmeCertificate.host }}
  {{- end}}
  issuerRef:
    kind: {{ .Values.acmeCertificate.issuerRef.kind }}
    name: {{ .Values.acmeCertificate.issuerRef.name }}
  secretName: {{ .Values.nameOverride }}
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
{{- end }}