apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.nameOverride }}-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - patch
  - get
  - update
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
  - get
  - update
  - list
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  - statefulsets
  verbs:
  - patch
  - get
  - update
  - list